name: food_snap
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  camera: ^0.11.1
  dio: ^5.8.0+1
  envied: ^1.1.1
  firebase_core: ^3.13.0
  firebase_ml_model_downloader: ^0.3.3+3
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.7
  image: ^4.5.4
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  provider: ^6.1.5
  tflite_flutter: ^0.11.0
  sqflite: ^2.4.2

dev_dependencies:
  build_runner: ^2.4.15
  change_app_package_name: ^1.5.0
  envied_generator: ^1.1.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/model/
